events { worker_connections 1024; }

http {
    upstream backend_servers {
        # 'backend' - це назва сервісу з docker-compose
        # Nginx автоматично знайде всі копії цього сервісу
        server backend:3000; 
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            # Додаємо заголовок, щоб бачити, який саме сервер обробив запит
            add_header X-Upstream $upstream_addr;
        }
    }
}